<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2009-04-25 20:13

$extensionPath = t3lib_extMgm::extPath('be_acl');
return array(
	'tx_beacl_userauthgroup'   => $extensionPath . 'res/class.tx_beacl_userauthgroup.php',
);
?>
